name: 'Gradle Publish'
description: 'Provides action to run a gradle publish'
inputs:
  javaVersion:
    description: 'Version of java'
    required: false
    default: '17'
  javaDistribution:
    description: 'Java distribution to use'
    required: false
    default: 'adopt'
  gitHubActor:
    description: 'GitHub Actor'
    required: true
  gitHubToken:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Gradle Build Env
      # TODO:  This is no good, this means that if say we had a action package published of
      # version 1.0.5, that this would always refer to the actions of master, and master could
      # be at a later version say 2.0.0, so eessentially this use is not guaranteed to reference
      # an action in the same release that it is published in unless the published release being
      # used is always the latest.
      # Ideally we would just reference the local action, and when the release was packaged
      # it would always reference that, or we somehow tie the release version into this
      # reference like `jonmadsen/composite-actions/gradleEnv@<Version Variable>
      uses: jonmadsen/composite-actions/gradleEnv@master
      with:
        javaVersion ${{ inputs.javaVersion }}
        javaDistribution: ${{ inputs.javaDistribution }}
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          publish
          -Pgithub_actor=${{ inputs.gitHubActor }}
          -Pgithub_token=${{ inputs.gitHubToken }}
