name: 'Gradle Env'
description: 'Provides action to set up environment for gradle based builds'
inputs:
  javaVersion:
    description: 'Version of java'
    required: false
    default: '17'
  javaDistribution:
    description: 'Java distribution to use'
    required: false
    default: 'adopt'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.javaVersion }}
        distribution: ${{ inputs.javaDistribution }}
