name: 'Gradle Build'
description: 'Provides action to run a gradle build'
inputs:
  javaVersion:
    description: 'Version of java'
    required: false
    default: '17'
  javaDistribution:
    description: 'Java distribution to use'
    required: false
    default: 'adopt'
runs:
  using: "composite"
  steps:
    - name: Gradle Build Env
      #     uses: jonmadsen/composite-actions/gradleEnv@v1
      uses: jonmadsen/composite-actions/gradleEnv@master
      #uses: /gradleEnv
      with:
        java-version: ${{ inputs.javaVersion }}
        distribution: ${{ inputs.javaDistribution }}
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          build
